"""add_wiki_cache_tables

Revision ID: 83814bca1097
Revises: 
Create Date: 2025-10-24 18:37:16.736443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '83814bca1097'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('universe', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('article_count', sa.Integer(), nullable=True),
    sa.Column('articles_with_images', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_universe_category_unique', 'category_cache', ['universe', 'category'], unique=True)
    op.create_index(op.f('ix_category_cache_category'), 'category_cache', ['category'], unique=False)
    op.create_index(op.f('ix_category_cache_id'), 'category_cache', ['id'], unique=False)
    op.create_index(op.f('ix_category_cache_universe'), 'category_cache', ['universe'], unique=False)
    op.create_table('image_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('url_hash', sa.String(length=32), nullable=False),
    sa.Column('local_path', sa.String(length=500), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('format', sa.String(length=10), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('cached_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_accessed', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cached_at', 'image_cache', ['cached_at'], unique=False)
    op.create_index('idx_is_valid', 'image_cache', ['is_valid'], unique=False)
    op.create_index('idx_url_hash', 'image_cache', ['url_hash'], unique=False)
    op.create_index(op.f('ix_image_cache_id'), 'image_cache', ['id'], unique=False)
    op.create_index(op.f('ix_image_cache_is_valid'), 'image_cache', ['is_valid'], unique=False)
    op.create_index(op.f('ix_image_cache_url_hash'), 'image_cache', ['url_hash'], unique=True)
    op.create_table('scraping_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('universe', sa.String(length=50), nullable=False),
    sa.Column('operation_type', sa.String(length=100), nullable=False),
    sa.Column('articles_processed', sa.Integer(), nullable=True),
    sa.Column('articles_created', sa.Integer(), nullable=True),
    sa.Column('articles_updated', sa.Integer(), nullable=True),
    sa.Column('images_downloaded', sa.Integer(), nullable=True),
    sa.Column('images_cached', sa.Integer(), nullable=True),
    sa.Column('images_failed', sa.Integer(), nullable=True),
    sa.Column('errors_count', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_operation_type', 'scraping_logs', ['operation_type'], unique=False)
    op.create_index('idx_started_at', 'scraping_logs', ['started_at'], unique=False)
    op.create_index('idx_status', 'scraping_logs', ['status'], unique=False)
    op.create_index(op.f('ix_scraping_logs_id'), 'scraping_logs', ['id'], unique=False)
    op.create_index(op.f('ix_scraping_logs_operation_type'), 'scraping_logs', ['operation_type'], unique=False)
    op.create_index(op.f('ix_scraping_logs_status'), 'scraping_logs', ['status'], unique=False)
    op.create_index(op.f('ix_scraping_logs_universe'), 'scraping_logs', ['universe'], unique=False)
    op.create_table('wiki_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('universe', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('image_cached', sa.Boolean(), nullable=True),
    sa.Column('image_cache_path', sa.String(length=500), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_accessed', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_expires_at', 'wiki_articles', ['expires_at'], unique=False)
    op.create_index('idx_image_cached', 'wiki_articles', ['image_cached'], unique=False)
    op.create_index('idx_title_universe', 'wiki_articles', ['title', 'universe'], unique=False)
    op.create_index('idx_unique_article', 'wiki_articles', ['title', 'universe'], unique=True)
    op.create_index('idx_universe_category', 'wiki_articles', ['universe', 'category'], unique=False)
    op.create_index(op.f('ix_wiki_articles_category'), 'wiki_articles', ['category'], unique=False)
    op.create_index(op.f('ix_wiki_articles_id'), 'wiki_articles', ['id'], unique=False)
    op.create_index(op.f('ix_wiki_articles_image_cached'), 'wiki_articles', ['image_cached'], unique=False)
    op.create_index(op.f('ix_wiki_articles_universe'), 'wiki_articles', ['universe'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wiki_articles_universe'), table_name='wiki_articles')
    op.drop_index(op.f('ix_wiki_articles_image_cached'), table_name='wiki_articles')
    op.drop_index(op.f('ix_wiki_articles_id'), table_name='wiki_articles')
    op.drop_index(op.f('ix_wiki_articles_category'), table_name='wiki_articles')
    op.drop_index('idx_universe_category', table_name='wiki_articles')
    op.drop_index('idx_unique_article', table_name='wiki_articles')
    op.drop_index('idx_title_universe', table_name='wiki_articles')
    op.drop_index('idx_image_cached', table_name='wiki_articles')
    op.drop_index('idx_expires_at', table_name='wiki_articles')
    op.drop_table('wiki_articles')
    op.drop_index(op.f('ix_scraping_logs_universe'), table_name='scraping_logs')
    op.drop_index(op.f('ix_scraping_logs_status'), table_name='scraping_logs')
    op.drop_index(op.f('ix_scraping_logs_operation_type'), table_name='scraping_logs')
    op.drop_index(op.f('ix_scraping_logs_id'), table_name='scraping_logs')
    op.drop_index('idx_status', table_name='scraping_logs')
    op.drop_index('idx_started_at', table_name='scraping_logs')
    op.drop_index('idx_operation_type', table_name='scraping_logs')
    op.drop_table('scraping_logs')
    op.drop_index(op.f('ix_image_cache_url_hash'), table_name='image_cache')
    op.drop_index(op.f('ix_image_cache_is_valid'), table_name='image_cache')
    op.drop_index(op.f('ix_image_cache_id'), table_name='image_cache')
    op.drop_index('idx_url_hash', table_name='image_cache')
    op.drop_index('idx_is_valid', table_name='image_cache')
    op.drop_index('idx_cached_at', table_name='image_cache')
    op.drop_table('image_cache')
    op.drop_index(op.f('ix_category_cache_universe'), table_name='category_cache')
    op.drop_index(op.f('ix_category_cache_id'), table_name='category_cache')
    op.drop_index(op.f('ix_category_cache_category'), table_name='category_cache')
    op.drop_index('idx_universe_category_unique', table_name='category_cache')
    op.drop_table('category_cache')
    # ### end Alembic commands ###
